config/routes.rb
Pyrite::Application.routes.draw do

  get 'projects/left' => "projects#left"
  post 'project/addUser' => "projects#addUser"
  post 'project/removeUser' => "projects#removeUser"
  
  resources :papers

  resources :projects

  devise_for :users

  root :to => "home#index"

  post 'projects/bibliography' => "projects#toBib"

  

end

app/models/paper.rb
class Paper < ActiveRecord::Base

  belongs_to :project

  def toBib(format)
    case format
      when "IEEE"
        return toIEEE
      when "APA"
        return toAPA
      when "MLA"
        return toMLA
      when "CHICAGO"
        return toCHICAGO
    end
  end


  def toIEEE
    bib = "#{authors}, \"#{title},\" "

    unless journal.nil? || journal.empty?
      bib += "#{journal}, "
    end

    unless volume.nil? || volume.empty?
      bib += "vol. #{volume}, "
    end

    unless issue.nil? || issue.empty?
      bib += "no. #{issue}, "
    end

    unless pages.nil? || pages.empty?
      bib += "pp. #{pages}, "
    end

    unless published_on.nil?
      bib += "#{published_on.strftime('%b. %Y.')}"
    end

    bib.strip!

    if bib[-1] == ","
      bib = bib[0..-2]
    end

    bib
  end

  def toAPA
    bib = "#{authors}, "

    unless published_on.nil?
      bib += "(#{published_on.strftime('%Y')}). "
    end

    bib += "#{title}. "

    unless journal.nil? || journal.empty?
      bib += "#{journal}. "
    end

    unless volume.nil? || volume.empty?
      bib += "vol. #{volume}"
    end

    unless issue.nil? || issue.empty?
      bib += "(#{issue}), "
    end

    unless pages.nil? || pages.empty?
      bib += "#{pages}"
    end

    bib.strip!

    if bib[-1] == "," || "."
      bib = bib[0..-1]
    end

    bib
  end

  def toMLA
    bib = "#{authors}. \"#{title}.\" "

    unless journal.nil? || journal.empty?
      bib += "#{journal} "
    end

    unless volume.nil? || volume.empty?
      bib += "#{volume}."
    end

    unless issue.nil? || issue.empty?
      bib += "#{issue} "
    end

    unless published_on.nil?
      bib += "(#{published_on.strftime('%b. %Y.')}): "
    end

    unless pages.nil? || pages.empty?
      bib += "#{pages}"
    end

    bib.strip!

    if bib[-1] == "." || ":"
      bib = bib[0..-1]
    end

    bib
  end

  def toCHICAGO
    bib = "#{authors}. \"#{title}.\" "

    unless journal.nil? || journal.empty?
      bib += "#{journal} "
    end

    unless volume.nil? || volume.empty?
      bib += "#{volume} "
    end

    unless issue.nil? || issue.empty?
      bib += "(#{issue}) "
    end

    unless published_on.nil?
      bib += "(#{published_on.strftime('%b %Y')}) : "
    end

    unless pages.nil? || pages.empty?
      bib += "#{pages}"
    end

    bib.strip!

    if bib[-1] == "." || ":"
      bib = bib[0..-1]
    end

    bib
  end

end

app/models/project.rb
class Project < ActiveRecord::Base

  has_and_belongs_to_many :users
  has_many :papers

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :ldap_authenticatable, :rememberable, :trackable

  has_and_belongs_to_many :projects
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  rescue_from DeviseLdapAuthenticatable::LdapException do |exception|
    render :text => exception, :status => 500
  end

  before_filter :authenticate_user!
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/papers_controller.rb
class PapersController < ApplicationController
  before_action :set_paper, only: [:show, :edit, :update, :destroy]

  # GET /papers
  # GET /papers.json
  def index
    @papers = Paper.all
  end

  # GET /papers/1
  # GET /papers/1.json
  def show
    render layout: false
  end

  # GET /papers/new
  def new
    @paper = Paper.new
  end

  # GET /papers/1/edit
  def edit
    render layout: false
  end

  # POST /papers
  # POST /papers.json
  def create
    @paper = Paper.new(paper_params)

    respond_to do |format|
      if @paper.save
        format.html { redirect_to @paper, notice: 'Paper was successfully created.' }
        format.json { render action: 'show', status: :created, location: @paper }
      else
        format.html { render action: 'new' }
        format.json { render json: @paper.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /papers/1
  # PATCH/PUT /papers/1.json
  def update
    respond_to do |format|
      if @paper.update(paper_params)
        format.html { redirect_to @paper, notice: 'Paper was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @paper.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /papers/1
  # DELETE /papers/1.json
  def destroy
    @paper.destroy
    respond_to do |format|
      format.html { redirect_to papers_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_paper
      @paper = Paper.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def paper_params
      params.require(:paper).permit(:title, :authors, :published_on, :journal, :volume, :issue, :pages, :url, :project_id)
    end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    render layout: false
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)
    @project.users = [current_user]
    @project.owner_id = current_user.id

    respond_to do |format|
      if @project.save
        format.html { redirect_to root_url, notice: 'Project was successfully created.' }
        format.json { render action: 'show', status: :created, location: @project }
      else
        format.html { render action: 'new' }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to root_url }
      format.json { head :no_content }
    end
  end

  def addUser
    @user = User.where(:login => params[:user_login])
    @project = Project.find(params[:project_id])
    @project.users.push(@user) unless @user.nil?
    render :partial => 'layouts/settings', :@project => @project

  end

  def removeUser
    @user = User.where(:login => params[:user_login]).first
    @project = Project.find(params[:project_id])
    @project.users.delete(@user) unless (@user.nil? || @user.id == @project.owner_id)
    render :partial => 'layouts/settings', :project => @project
  end

  def toBib
    render 'projects/bibliography_format', layout: false
  end

  def left
    render 'layouts/left_navbar', layout: false
  end

  def settings
    render 'projects/settings', layout: false
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:name, :owner_id, :user_login)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/papers_helper.rb
module PapersHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/home/index.html.haml
- if current_user.projects.empty?
  .lead.text-center
    Project information will be shown once a project is created.
    Use the left navbar to create a project.
- else
  =  render 'projects/show', :@project => current_user.projects.order("updated_at DESC").first

app/views/layouts/_bibliography.html.haml
%h2 Bibliography Generator
= form_tag "/projects/bibliography", remote: true, id: 'bibliography_format' do
  .form-group
    = radio_button_tag 'format', 'IEEE', checked: true
    IEEE

  .form-group
    = radio_button_tag 'format', 'APA'
    APA
    
  .form-group
    = radio_button_tag 'format', 'CHICAGO'
    Chicago

  .form-group
    = radio_button_tag 'format', 'MLA'
    MLA

  = hidden_field_tag :project, @project.id
    
  = submit_tag 'Generate Bibliography', class: 'btn btn-success'

#bibliography_format_response{style: "padding-top: 40px;"}

:javascript
  $(function() {
    $("#bibliography_format")
      .on("ajax:success", function(event, data, status, response) {
        $( "#bibliography_format_response" ).html( response.responseText );
    });
  });

app/views/layouts/_left_navbar.html.haml
%h2{:style => "margin-top: 0px;"} Projects
- current_user.projects.order("updated_at DESC").each_with_index do |project, index|
  .input-group
    %span.form-control.project{readonly: (true if index == 0), data: {project: project.id}}= project.name
    %span.input-group-addon= link_to 'x', project, method: :delete

= render 'projects/form', :@project => Project.new

:javascript
  $(function() {
    $("span[data-project]").on('click', function() {
      $('#main').load( "projects/" + $(this).data('project') );
      $(".project[data-project!=' + $(this).data('project') + ']").attr('readonly', false);
      $(this).attr('readonly', true);
    });
  });

app/views/layouts/_settings.html.haml
%h1 Settings
%h3 Rename Project
= form_for @project, remote: true, data: {edit_project: true} do |f|
  .input-group
    = f.text_field :name, :class => "form-control", :placeholder => @project.name
    %span.input-group-addon.pointer{style: "max-width: 60px;", data: {edit_project_btn: true}} Save

%h3 Users on project
- @project.users.each do |user|
  = form_tag "/project/removeUser", remote: true, data: {remove_user: true} do
    .input-group
      = text_field_tag :user_login, user.login, :readonly => true, class: "form-control"
      = hidden_field_tag :project_id, @project.id
      .input-group-addon.pointer -

= form_tag "/project/addUser", remote: true, data: {add_user: true} do
  .input-group
    = hidden_field_tag :project_id, @project.id
    = text_field_tag :user_login, "", placeholder: "abc1234", class: "form-control"
    .input-group-addon.pointer +

:javascript
  form = $("*[data-edit-project]");
  form.on("ajax:success", function(event, data, status, response) {
      $( "#left" ).load( "/projects/left" );
  });
  $("*[data-edit-project-btn]").on('click', function() {
    form.submit();
  });

:javascript
  $("*[data-add-user],*[data-remove-user]")
    .on("ajax:success", function(event, data, status, response) {
      $( "#settings" ).html( response.responseText );
  });

:javascript
  $("*[data-remove-user]").on('click', function() {  
    $(this).submit();
  });

app/views/layouts/_top_navbar.html.haml
%nav.navbar.navbar-default.navbar-static-top{:role => "navigation"}
  .container
    .navbar-header
      %button.navbar-toggle{"data-target" => ".navbar-ex7-collapse", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      %a.navbar-brand{:href => "#"} BetterBib
    .collapse.navbar-collapse.navbar-ex7-collapse
      %ul.nav.navbar-nav.pull-right
        %li
          =link_to "Logout", destroy_user_session_path, :action=>"get"
      %form.navbar-form.navbar-right{role: "search"}
        .form-group
          %input.form-control{placeholder: "Search", type: "text"}

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title BetterBib
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
  %body  
    - if user_signed_in?
      = render 'layouts/top_navbar'
      .container
        .row
          .col-lg-3
            #left
              = render 'layouts/left_navbar'
          .col-lg-6
            #main
              = yield
          .col-lg-3
            #right
    - else
      = yield

app/views/layouts/left_navbar.html.haml
= render :partial => 'layouts/left_navbar'

app/views/papers/_form.html.haml
= form_for @paper, remote: true, html: {id: 'edit_paper'} do |f|
  - if @paper.errors.any?
    #error_explanation
      %h2= "#{pluralize(@paper.errors.count, "error")} prohibited this paper from being saved:"
      %ul
        - @paper.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :title
    = f.text_field :title, class: 'form-control'
  .field
    = f.label :authors
    = f.text_field :authors, class: 'form-control'
  .field
    = f.label :published_on
    .input-group
      = f.text_field :published_on, class: 'form-control', readonly: true
      .input-group-addon
        %i.glyphicon.glyphicon-calendar
  .field
    = f.label :journal
    = f.text_field :journal, class: 'form-control'
  .field
    = f.label :volume
    = f.text_field :volume, class: 'form-control'
  .field
    = f.label :issue
    = f.text_field :issue, class: 'form-control'
  .field
    = f.label :pages
    = f.text_field :pages, class: 'form-control'
  .field
    = f.label :url
    = f.text_field :url, class: 'form-control'
    = f.hidden_field :project_id
  .actions
    = f.submit 'Save', class: 'btn btn-primary'

- unless @paper.project.nil?
  :javascript
    $("#edit_paper")
      .on("ajax:success", function(event, data, status, response) {
        $( "#main" ).load( "projects/#{@paper.project.id}" );
    });

:javascript
  $(function() {
    $('#paper_published_on').datepicker({ dateFormat: 'yy-mm-dd' });
  });

app/views/papers/_form_light.html.haml
= form_for @paper, remote: true, html: {id: 'new_paper_light'} do |f|
  %tr
    %td= f.hidden_field :project_id, value: project.id
    %td= f.text_field :title, placeholder: 'Title', class: 'form-control'
    %td= f.text_field :authors, placeholder: 'Author', class: 'form-control'
    %td= f.text_field :journal, placeholder: 'Journal', class: 'form-control'
    %td= f.submit '+', :class => "btn btn-primary btn-fixed"

:javascript
  $("#new_paper_light")
    .on("ajax:success", function(event, data, status, response) {
      $( "#main" ).load( "projects/#{project.id}" );
  });

app/views/papers/edit.html.haml
= render 'form'

app/views/papers/index.html.haml
%h1 Listing papers

%table
  %tr
    %th Title
    %th Authors
    %th Published on
    %th Journal
    %th Volume
    %th Issue
    %th Pages
    %th Url
    %th Project
    %th
    %th
    %th

  - @papers.each do |paper|
    %tr
      %td= paper.title
      %td= paper.authors
      %td= paper.published_on
      %td= paper.journal
      %td= paper.volume
      %td= paper.issue
      %td= paper.pages
      %td= paper.url
      %td= paper.project_id
      %td= link_to 'Show', paper
      %td= link_to 'Edit', edit_paper_path(paper)
      %td= link_to 'Destroy', paper, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Paper', new_paper_path

app/views/papers/new.html.haml
%h1 New paper

= render 'form'

= link_to 'Back', papers_path

app/views/papers/show.html.haml
%p#notice= notice

%p
  %b Title:
  = @paper.title
%p
  %b Authors:
  = @paper.authors
%p
  %b Published on:
  = @paper.published_on
%p
  %b Journal:
  = @paper.journal
%p
  %b Volume:
  = @paper.volume
%p
  %b Issue:
  = @paper.issue
%p
  %b Pages:
  = @paper.pages
%p
  %b Url:
  = @paper.url
%p
  %b Project:
  = @paper.project_id

= link_to 'Edit', edit_paper_path(@paper)
\|
= link_to 'Back', papers_path

app/views/projects/_form.html.haml
= form_for @project, html: {id: "newproject"} do |f|
  - if @project.errors.any?
    #error_explanation
      %h2= "#{pluralize(@project.errors.count, "error")} prohibited this project from being saved:"
      %ul
        - @project.errors.full_messages.each do |msg|
          %li= msg
  .input-group
    = f.text_field :name, :class => "form-control", :placeholder => "Name"
    %span.input-group-addon= link_to '+', "#", :onclick => "$('#newproject').submit()"

app/views/projects/_show.html.haml
%ul.nav.nav-tabs
  %li.active
    %a{"data-toggle" => "tab", href: "#papers"} Papers
  %li
    %a{"data-toggle" => "tab", href: "#bibliography"} Bibliography
  %li
    %a{"data-toggle" => "tab", href: "#settings"} Settings
.tab-content
  #papers.tab-pane.active
    %table.table.table-hover
      %thead
        %tr
          %th #
          %th Title
          %th Author
          %th Journal
          %th 
      %tbody
        - @project.papers.each_with_index do |paper, i|
          %tr{data: {paper_id: paper.id}}
            %td= i+1
            %td= paper.title
            %td= paper.authors
            %td= paper.journal
            %td= button_to '-', paper, method: :delete, :remote => true, data:{confirm: 'Are you sure?', paperdelete: true }, class: "btn btn-danger btn-fixed", :form_class => "paper_delete"
        = render 'papers/form_light', :@paper => Paper.new, :project => @project
  #bibliography.tab-pane
    = render 'layouts/bibliography', :project => @project
  #settings.tab-pane
    = render 'layouts/settings', :project => @project

:javascript
  $(function() {
    $(".paper_delete").on("ajax:success", function(event, data, status, response) {
      $( "#main" ).load( "projects/#{@project.id}" );
    });
  });

:javascript
  $(function() {
    $('*[data-paper-id]').on('click', function() {
      $('#right').load('papers/' + $(this).data('paper-id') + '/edit');
    });
  });

app/views/projects/bibliography_format.html.haml
- Project.find(params[:project]).papers.each do |paper|
  %p= paper.toBib(params[:format])

app/views/projects/edit.html.haml
%h1 Editing project

= render 'form'

= link_to 'Show', @project
\|
= link_to 'Back', projects_path

app/views/projects/index.html.haml
%h1 Listing projects

%table
  %tr
    %th Name
    %th Owner
    %th
    %th
    %th

  - @projects.each do |project|
    %tr
      %td= project.name
      %td= project.owner_id
      %td= link_to 'Show', project
      %td= link_to 'Edit', edit_project_path(project)
      %td= link_to 'Destroy', project, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Project', new_project_path

app/views/projects/new.html.haml
%h1 New project

= render 'form'

= link_to 'Back', projects_path

app/views/projects/show.html.haml
= render :partial => 'projects/show', :@project => @project